name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: write  # Allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2.2.0
        with:
          args: |
            -Dsonar.projectKey=tibisay56_placetogrow
            -Dsonar.organization=TibisayBarroso
            -Dsonar.host.url=https://sonarcloud.io
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Run SonarCloud analysis
        run: sonar-scanner
          
      
